# Generated by Django 4.2 on 2023-06-20 14:01

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0003_remove_user_is_admincheck'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
