# Generated by Django 4.2 on 2023-06-20 14:19

from django.db import migrations, models


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0005_remove_user_is_check'),
    ]

    operations = [
        migrations.AddField(
            model_name='user',
            name='is_check',
            field=models.BooleanField(default=False),
        ),
    ]
