# Generated by Django 4.2 on 2023-06-20 14:21

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('common', '0006_user_is_check'),
    ]

    operations = [
        migrations.RenameField(
            model_name='user',
            old_name='is_check',
            new_name='is_student',
        ),
    ]
