# Generated by Django 4.2 on 2023-06-19 17:12

from django.db import migrations


class Migration(migrations.Migration):

    dependencies = [
        ('locker', '0001_initial'),
    ]

    operations = [
        migrations.RemoveField(
            model_name='users',
            name='student_number',
        ),
        migrations.DeleteModel(
            name='Lockers',
        ),
        migrations.DeleteModel(
            name='Users',
        ),
    ]
